export const AdminActionType = {
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_UNSUSPENDED: 'USER_UNSUSPENDED',
  TAG_DEACTIVATED: 'TAG_DEACTIVATED',
  TAG_REACTIVATED: 'TAG_REACTIVATED',
  TAG_BATCH_GENERATED: 'TAG_BATCH_GENERATED',
  TAG_BATCH_DELETED: 'TAG_BATCH_DELETED',
  TAG_CSV_IMPORTED: 'TAG_CSV_IMPORTED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  REFUND_ISSUED: 'REFUND_ISSUED',
  MODERATION_ACTION: 'MODERATION_ACTION',
  QR_GENERATED: 'QR_GENERATED',
  ORDER_TAGS_ACTIVATED: 'ORDER_TAGS_ACTIVATED',
} as const;

export type AdminActionType = (typeof AdminActionType)[keyof typeof AdminActionType];