export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',

  // Tags
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_ALREADY_ACTIVATED: 'TAG_ALREADY_ACTIVATED',
  TAG_NOT_ACTIVE: 'TAG_NOT_ACTIVE',
  TAG_DEACTIVATED: 'TAG_DEACTIVATED',
  TAG_NOT_OWNED: 'TAG_NOT_OWNED',

  // Communication
  RELAY_UNAVAILABLE: 'RELAY_UNAVAILABLE',
  RELAY_RATE_LIMITED: 'RELAY_RATE_LIMITED',
  WHATSAPP_NOT_ENABLED: 'WHATSAPP_NOT_ENABLED',
  OWNER_UNREACHABLE: 'OWNER_UNREACHABLE',

  // Subscription
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',

  // Store / Orders
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  CHECKOUT_FAILED: 'CHECKOUT_FAILED',

  // Media
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // General
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
