DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'QrLayout') THEN
    CREATE TYPE "QrLayout" AS ENUM ('STANDARD', 'WINDSHIELD_CARD');
  END IF;
END
$$;

ALTER TABLE "tags"
  ADD COLUMN IF NOT EXISTS "qrLayout" "QrLayout" NOT NULL DEFAULT 'STANDARD';

ALTER TABLE "tag_batches"
  ADD COLUMN IF NOT EXISTS "qrLayout" "QrLayout" NOT NULL DEFAULT 'STANDARD';
